### ISSUE TITLE
[Nette\Application\BadRequestException] No route for HTTP request.  when running tests

### ISSUE THREAD

**Issue by dakorpar** [Arachne/Codeception#5]
I'm getting this error when running codecept run functional

> Functional Tests (1) ---------------------------------------
> ## E Test1Cest: Verify homepage (1.16s)
> 
> Time: 14.23 seconds, Memory: 34.00MB
> 
> There was 1 error:
> ---
> 
> 1) Test1Cest: Verify homepage
>  Test  tests\functional\Test1Cest.php:tryToTest
> 
>   [Nette\Application\BadRequestException] No route for HTTP request.  
> 
> Scenario Steps:
> 1. $I->amOnPage("/") at tests\functional\Test1Cest.php:18
> # 1  C:\Development\project\web\vendor\nette\application\src\Application\Application.php:83
> # 2  C:\Development\project\web\vendor\arachne\codeception\src\Connector\NetteConnector.php:73
> # 3  C:\Development\project\web\vendor\symfony\browser-kit\Client.php:315
> # 4  Codeception\Lib\InnerBrowser->amOnPage
> # 5  C:\Development\project\web\tests_support_generated\FunctionalSuiteTesterActions.php:142
> # 6  C:\Development\project\web\tests\functional\Test1Cest.php:18
> # 7  Test1Cest->tryToTest

Homepage HTML is outputed in console when calling command also, and HTML is correct of homepage , and links looks good there also... 
You need some more info on it or you have a clue what could it be?

My Test1Cept looks like:

```

class Test1Cest
{
    public function _before(FunctionalSuiteTester $I)
    {
    }

    public function _after(FunctionalSuiteTester $I)
    {
    }

    // tests
    public function tryToTest(FunctionalSuiteTester $I)
    {
        $I->wantTo('Verify homepage');
        $I->amOnPage('/');
        $I->see('Welcome');
    }
}

```

and _bootstrap file:

```
define('WWW_DIR', __DIR__ . '/../../www');
define('APP_DIR', __DIR__ . '/../../app');
define('ESHOPID', 1);
$_SERVER['REMOTE_ADDR'] = '127.0.0.1';
$_SERVER['HTTP_HOST'] = 'project.local';
$_SERVER['REQUEST_METHOD'] = 'GET';
$_SERVER['HTTPS'] = TRUE;
require __DIR__ . '/../../app/bootstrap.php';
return $container;
```

I'm just wanting this to work then I'll play with correct bootstrap, different db connection and etc...

and functional.yml

```
error_level: "E_ALL"
class_name: FunctionalSuiteTester
modules:
    enabled:
        - Arachne\Codeception\Module\NetteApplicationModule
        - Arachne\Codeception\Module\NetteDIModule:
            tempDir: ../../temp/cache/functional
            configFiles:
                - ../../app/config/config.neon
                - ../../app/config/config.local.neon
                - config.neon
```
