### ISSUE TITLE
Absolute paths for config files

### ISSUE THREAD

**Issue by fmasa** [Arachne/Codeception#6]
Hi,
I really like your extension as it made my life easier.

One of the things that would be great would be support for absolute paths of config files. Currently I have nested test suite with different config files and navigating to those files makes things messy.

In `NetteDiModule::createContainer` we can check whether `$file` is absolute path and prepend path only if it isn't.

What do you think? I can prepare PR if you think it's worth it. :slightly_smiling_face: 

```
$configFiles = is_array($this->configFiles) ? $this->configFiles : $this->config['configFiles'];
foreach ($configFiles as $file) {
    $configurator->addConfig($this->path.'/'.$file);
}
```

**Comment by enumag** [comment]
Is navigating to other files really that messy? I don't think a few ../ is a problem. This is what my `functional.suite.dist.yml` looks like. Is your file worse than this?

```
class_name: FunctionalTester
modules:
    enabled:
        - Db
        - Arachne\Codeception\Module\NetteApplicationModule
        - Arachne\Codeception\Module\NetteDIModule:
            removeDefaultExtensions: true
            appDir: ../../app
            tempDir: ../_temp/functional
            wwwDir: ../../www
            configFiles:
                - ../../app/config/config.neon
                - config/config.neon
                - config/fixtures.neon
                - config/local.neon
        - App\Codeception\Module\Email:
            depends: Db

```

I'm not quite convinced that supporting absolute paths is a good idea. It may not be completely clear what the root directory refers to. Filesystem root? Root of this project? Tests root? The directory of the testing suite in question? The relative paths are from the file they are written in so they should be clear.
